### ISSUE TITLE
Failed to started lib2p

### ISSUE THREAD

**Issue by pravintargaryen** [libp2p/universal-connectivity#182]
When visiting https://universal-connectivity.vercel.app/, getting this error in the console

![1](https://github.com/user-attachments/assets/8c0bce6f-5c73-46de-ac38-0475f70fb04f)

**Comment by 2color** [comment]
When the page loads, it makes two requests to `delegated-ipfs.dev` in order to resolve the PeerIDs of the bootstrappers to their multiaddrs. 

These requests are getting blocked by your browser. Do you have any plugins that might prevent those requests? ([see this thread for more reasons on why it might be getting blocked](https://stackoverflow.com/questions/23341765/getting-neterr-blocked-by-client-error-on-some-ajax-calls))

**Comment by pravintargaryen** [comment]
@2color I disabled my adblocker and it works. Thanks
